{
  "env": {
    "pkg_manager": "apt",
    "instructions": [
      [
        "base",
        "ubuntu:bionic-20180821"
      ],
      [
        "ants",
        {
          "version": "2.2.0"
        }
      ],
      [
        "miniconda",
        {
          "use_env": "base",
          "conda_install": ["python=3.6", "nipype=1.1.3"]
        }
      ]
    ]
  },
  "build": {
    "pre-install": "pip install --upgrade pip setuptools wheel",
    "install": "pip wheel --no-deps package/",
    "package": "niflow_ants_brainextraction-{version}-dist-py3-none-any.whl"
  }
}
